package cayng.data.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.NumericIdProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.exp.property.StringProperty;

import cayng.data.Person;

/**
 * Class _Person was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Person extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<Person> SELF = PropertyFactory.createSelf(Person.class);

    public static final NumericIdProperty<Integer> ID_PK_PROPERTY = PropertyFactory.createNumericId("id", "Person", Integer.class);
    public static final String ID_PK_COLUMN = "id";

    public static final StringProperty<String> NOM = PropertyFactory.createString("nom", String.class);

    protected String nom;
    
    //test complétion apres un point
    
	/*
	 * public void test() { ObjectSelect.query(Person.class) .where(Person.NOM. }
	 */

    public void setNom(String nom) {
        beforePropertyWrite("nom", this.nom, nom);
        this.nom = nom;
    }

    public String getNom() {
        beforePropertyRead("nom");
        return this.nom;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "nom":
                return this.nom;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "nom":
                this.nom = (String)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.nom);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.nom = (String)in.readObject();
    }

}
